In [1]:
#東京証券取引所から銘柄一覧データを取得する
#https://www.jpx.co.jp/markets/statistics-equities/misc/01.html

import pandas as pd

tse_list = pd.read_excel('data_j.xls', header=0)

In [2]:
tse_list

            日付   コード  ... 規模コード           規模区分
0     20211130  1301  ...     7  TOPIX Small 2
1     20211130  1305  ...     -              -
2     20211130  1306  ...     -              -
3     20211130  1308  ...     -              -
4     20211130  1309  ...     -              -
...        ...   ...  ...   ...            ...
4132  20211130  9993  ...     7  TOPIX Small 2
4133  20211130  9994  ...     7  TOPIX Small 2
4134  20211130  9995  ...     7  TOPIX Small 2
4135  20211130  9996  ...     -              -
4136  20211130  9997  ...     6  TOPIX Small 1

[4137 rows x 10 columns]

In [3]:
tse1 = tse_list[tse_list['市場・商品区分'] == '市場第一部（内国株）']
tse1

            日付   コード     銘柄名     市場・商品区分  ... 17業種コード  17業種区分 規模コード           規模区分
0     20211130  1301      極洋  市場第一部（内国株）  ...       1     食品      7  TOPIX Small 2
19    20211130  1332    日本水産  市場第一部（内国株）  ...       1     食品      4   TOPIX Mid400
20    20211130  1333  マルハニチロ  市場第一部（内国株）  ...       1     食品      4   TOPIX Mid400
26    20211130  1352    ホウスイ  市場第一部（内国株）  ...      13  商社・卸売      7  TOPIX Small 2
37    20211130  1375  雪国まいたけ  市場第一部（内国株）  ...       1     食品      6  TOPIX Small 1
...        ...   ...     ...         ...  ...     ...     ...   ...            ...
4131  20211130  9991    ジェコス  市場第一部（内国株）  ...      13  商社・卸売      7  TOPIX Small 2
4132  20211130  9993    ヤマザワ  市場第一部（内国株）  ...      14     小売      7  TOPIX Small 2
4133  20211130  9994     やまや  市場第一部（内国株）  ...      14     小売      7  TOPIX Small 2
4134  20211130  9995   グローセル  市場第一部（内国株）  ...      13  商社・卸売      7  TOPIX Small 2
4136  20211130  9997    ベルーナ  市場第一部（内国株）  ...      14     小売      6  TOPIX Small 1

[2184 rows x 10 columns]

In [4]:
# TOPIX500の銘柄を抽出する

# '市場・商品区分'列のデータが”市場第一部（内国株）”だけの行を選択する
tse1 = tse_list[tse_list['市場・商品区分'] == '市場第一部（内国株）']

# ”規模区分”列が"core30 Large70 Mid400”の行だけを選択する
topix500 = tse1[(tse1['規模区分'] == 'TOPIX Core30') | #パイプライン
                (tse1['規模区分'] == 'TOPIX Large70') |
                (tse1['規模区分'] == 'TOPIX Mid400')]

topix500

            日付   コード             銘柄名  ...         17業種区分 規模コード           規模区分
19    20211130  1332            日本水産  ...            食品      4   TOPIX Mid400
20    20211130  1333          マルハニチロ  ...            食品      4   TOPIX Mid400
63    20211130  1414  ショーボンドホールディングス  ...         建設・資材      4   TOPIX Mid400
64    20211130  1417   ミライト・ホールディングス  ...         建設・資材      4   TOPIX Mid400
166   20211130  1605           ＩＮＰＥＸ  ...       エネルギー資源      4   TOPIX Mid400
...        ...   ...             ...  ...            ...   ...            ...
4111  20211130  9962       ミスミグループ本社  ...         商社・卸売      4   TOPIX Mid400
4125  20211130  9983     ファーストリテイリング  ...            小売      2  TOPIX Large70
4126  20211130  9984      ソフトバンクグループ  ...  情報通信・サービスその他      1   TOPIX Core30
4128  20211130  9987            スズケン  ...         商社・卸売      4   TOPIX Mid400
4129  20211130  9989          サンドラッグ  ...            小売      4   TOPIX Mid400

[500 rows x 10 columns]

In [5]:
# 33業種コード,33業種区分ごとの銘柄数を算出
#特定の値がいくつあるか数えるとき、groupby() してから size()
category_count = topix500.groupby(['33業種コード','33業種区分']).size()
print(category_count)

33業種コード  33業種区分
50       水産・農林業         2
1050     鉱業             1
2050     建設業           20
3050     食料品           28
3100     繊維製品           5
3150     パルプ・紙          4
3200     化学            44
3250     医薬品           21
3300     石油・石炭製品        3
3350     ゴム製品           4
3400     ガラス・土石製品       8
3450     鉄鋼             7
3500     非鉄金属           7
3550     金属製品           6
3600     機械            32
3650     電気機器          51
3700     輸送用機器         19
3750     精密機器          10
3800     その他製品         10
4050     電気・ガス業        13
5050     陸運業           25
5100     海運業            3
5150     空運業            2
5200     倉庫・運輸関連業       2
5250     情報・通信業        38
6050     卸売業           23
6100     小売業           32
7050     銀行業           23
7100     証券、商品先物取引業     4
7150     保険業            6
7200     その他金融業         8
8050     不動産業          12
9050     サービス業         27
dtype: int64

In [6]:
# 33業種コード,33業種区分を抽出
#グループ化して辞書型で表示する。
industry_category = topix500.groupby(['33業種コード','33業種区分']).groups.keys()
print(industry_category)

dict_keys([(50, '水産・農林業'), (1050, '鉱業'), (2050, '建設業'), (3050, '食料品'), (3100, '繊維製品'), (3150, 'パルプ・紙'), (3200, '化学'), (3250, '医薬品'), (3300, '石油・石炭製品'), (3350, 'ゴム製品'), (3400, 'ガラス・土石製品'), (3450, '鉄鋼'), (3500, '非鉄金属'), (3550, '金属製品'), (3600, '機械'), (3650, '電気機器'), (3700, '輸送用機器'), (3750, '精密機器'), (3800, 'その他製品'), (4050, '電気・ガス業'), (5050, '陸運業'), (5100, '海運業'), (5150, '空運業'), (5200, '倉庫・運輸関連業'), (5250, '情報・通信業'), (6050, '卸売業'), (6100, '小売業'), (7050, '銀行業'), (7100, '証券、商品先物取引業'), (7150, '保険業'), (7200, 'その他金融業'), (8050, '不動産業'), (9050, 'サービス業')])

In [7]:
import datetime
from datetime import date,timedelta

In [8]:
!pip install pandas-datareader
import pandas_datareader.data as web

Requirement already satisfied: pandas-datareader in /usr/local/lib/python3.7/dist-packages (0.9.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from pandas-datareader) (4.2.6)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.7/dist-packages (from pandas-datareader) (1.1.5)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.7/dist-packages (from pandas-datareader) (2.23.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas-datareader) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas-datareader) (2.8.2)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas-datareader) (1.19.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas-datareader) (1.15.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (2.10)

In [9]:
# 2020/11/2〜2021/2/5の株価を取得する
base_date = datetime.datetime(2020, 1, 27)
end_date=datetime.datetime(2021, 2, 5)

In [10]:
# 業種単位の株価上昇率格納用のDataFrameを用意する
category_df = None

In [11]:
# 業種ごとに変動率を計算する
for category in industry_category:
    
    category_code = category[0]     # 33業種コード
    category_class = category[1]    # 33業種区分
    
    # 指定した業種の銘柄を抽出
    brands = topix500[topix500['33業種区分'] == category_class]
    
    # 銘柄コードの末尾に.JPを付加する
    symbols = []
    for code in brands['コード']:
        symbols.append('{0:d}.JP'.format(code))

    # 指定銘柄コードの株価を取得する
    stock_price = web.DataReader(symbols, 'stooq', start=base_date, end=end_date)
    print(stock_price)

Attributes   Close             High           ...    Open            Volume
Symbols    1332.JP  1333.JP 1332.JP  1333.JP  ... 1332.JP  1333.JP  1332.JP 1333.JP
Date                                          ...
2021-02-05  485.61  2409.84  486.59  2412.80  ...  447.19  2359.60  7523916  189806
2021-02-04  445.22  2359.60  450.15  2372.41  ...  446.21  2350.73  1660803   97034
2021-02-03  446.21  2359.60  446.21  2359.60  ...  435.37  2316.25  2429733  132255
2021-02-02  435.37  2313.29  437.34  2314.28  ...  435.37  2305.41  1199892  120075
2021-02-01  436.36  2302.45  438.33  2334.97  ...  432.42  2315.26  1618671  117334
...            ...      ...     ...      ...  ...     ...      ...      ...     ...
2020-01-31  582.69  2546.94  586.56  2555.66  ...  577.85  2537.24  2200373  180742
2020-01-30  573.98  2509.15  584.63  2549.84  ...  582.69  2533.37  2412992  333821
2020-01-29  588.50  2558.56  589.47  2558.56  ...  578.81  2538.22  2547197  216870
2020-01-28  581.72  2535.31  583.65  2558.56  ...  572.05  2557.59  2339951  312969
2020-01-27  576.88  2564.37  577.85  2581.81  ...  572.05  2581.81  2666834  221928

[252 rows x 10 columns]
Attributes   Close    High     Low    Open    Volume
Symbols    1605.JP 1605.JP 1605.JP 1605.JP   1605.JP
Date
2021-02-05  642.87  651.73  630.07  631.05  11276074
2021-02-04  626.13  634.01  623.18  631.05   9809720
2021-02-03  618.26  618.26  609.39  611.36   7564785
2021-02-02  601.52  608.41  593.64  597.58   6669695
2021-02-01  591.67  599.55  588.72  596.60   6051706
...            ...     ...     ...     ...       ...
2020-01-31  967.17  981.24  966.69  980.77   5769296
2020-01-30  977.96  986.88  970.44  979.36   3933994
2020-01-29  983.59  989.22  973.73  977.96   4855001
2020-01-28  970.44  977.02  958.72  976.55   6972232
2020-01-27  988.28  995.78  973.73  979.36   4599710

[252 rows x 5 columns]
Attributes    Close                    ...    Volume
Symbols     1414.JP  1417.JP  1721.JP  ...   1951.JP   1959.JP    1963.JP
2020-01-27  4446.24  1599.29  2993.23  ...  289269.0  177455.0  1185336.0
2020-01-28  4392.78  1570.73  2979.04  ...  367137.0  177772.0  1505012.0
2020-01-29  4426.81  1572.64  2997.95  ...  281514.0  123773.0  1627831.0
2020-01-30  4363.63  1555.51  2974.31  ...  440224.0  182431.0  1280953.0
2020-01-31  4383.07  1566.93  3016.87  ...  255382.0  191960.0  1471572.0
...             ...      ...      ...  ...       ...       ...        ...
2021-02-01  4463.80  1668.13  3062.87  ...  266015.0  221299.0  1938884.0
2021-02-02  4513.18  1684.75  3126.08  ...  239444.0  152521.0  1670043.0
2021-02-03  4523.05  1670.09  3174.69  ...  226469.0  133046.0  1524375.0
2021-02-04  4572.43  1674.97  3155.25  ...  237384.0  136941.0  1533958.0
2021-02-05  4542.81  1651.52  3223.31  ...  275283.0  167486.0  2148812.0

[252 rows x 95 columns]
Attributes    Close                             ...  Volume
Symbols     2002.JP  2201.JP  2206.JP  2212.JP  ... 2871.JP 2875.JP 2897.JP  2914.JP
Date                                            ...
2021-02-05  1759.44  4156.79  4582.53  1912.00  ...  712286  427202  524962  3812134
2021-02-04  1732.96  4112.57  4562.69  1899.00  ...  529489  398234  778777  3747317
2021-02-03  1762.39  4112.57  4592.44  1925.00  ...  908901  373942  811927  4080572
2021-02-02  1710.41  3999.56  4542.85  1918.00  ...  522478  538296  342988  3115946
2021-02-01  1731.00  4009.38  4523.01  1920.00  ...  641667  646241  426519  3756797
...             ...      ...      ...      ...  ...     ...     ...     ...      ...
2020-01-31  1807.71  5103.50  4585.24  2062.37  ...  557352  759921  267160  5873441
2020-01-30  1729.74  5045.40  4550.98  2025.82  ...  774723  287883  142240  4492616
2020-01-29  1749.95  5093.82  4604.81  2039.65  ...  345033  234576  176476  4444054
2020-01-28  1720.13  5045.40  4599.91  2039.65  ...  354106  252104  164656  5906926
2020-01-27  1727.82  5093.82  4619.48  2043.60  ...  536830  176731  153346  5608896

[252 rows x 140 columns]
Attributes    Close                   ...    Volume
Symbols     3101.JP  3401.JP 3402.JP  ...   3402.JP 3591.JP 8111.JP
Date                                  ...
2021-02-05  1307.97  1920.87  713.34  ...   4927278  179057  185567
2021-02-04  1292.40  1920.87  711.17  ...   5495584  250029  187081
2021-02-03  1302.13  1932.52  718.55  ...  10341793  313782  140461
2021-02-02  1278.77  1883.99  694.95  ...   5896256  224508   90614
2021-02-01  1289.48  1903.40  677.45  ...   5131328  356690   79111
...             ...      ...     ...  ...       ...     ...     ...
2020-01-31  1424.88  1885.22  694.90  ...   4484862   98462  194011
2020-01-30  1411.72  1868.03  695.09  ...   7214391   74620  235868
2020-01-29  1428.63  1884.26  694.71  ...   4548938   58932  166310
2020-01-28  1412.65  1866.13  689.92  ...   6108803  104241  248904
2020-01-27  1427.69  1893.81  695.29  ...   9330494   70079  225989

[252 rows x 25 columns]
Attributes   Close                            ...   Volume
Symbols    3861.JP  3863.JP  3880.JP 3941.JP  ...  3861.JP  3863.JP 3880.JP  3941.JP
Date                                          ...
2021-02-05  628.36  1342.34  1823.59  882.25  ...  3485023  1110551  204625   660705
2021-02-04  628.36  1305.46  1824.58  876.40  ...  1746292   530291  136417   875503
2021-02-03  629.34  1308.37  1844.40  863.73  ...  2370143   574181  153569   546536
2021-02-02  636.20  1280.22  1856.30  857.88  ...  2617395   751082  171630   584797
2021-02-01  629.34  1257.90  1851.34  859.84  ...  3397157   605811  155891   625521
...            ...      ...      ...     ...  ...      ...      ...     ...      ...
2020-01-31  539.76  1695.43  1427.04  733.22  ...  2660349   255821  128612   813458
2020-01-30  535.94  1685.97  1416.23  726.59  ...  2832637   436768  160561   986051
2020-01-29  549.29  1717.17  1432.94  739.85  ...  2216784   344020  173075   991856
2020-01-28  543.57  1706.78  1425.07  739.85  ...  3474288   514815  296497  1121803
2020-01-27  548.34  1719.07  1423.10  754.06  ...  2725574   334609  213775   828869

[252 rows x 20 columns]
Attributes    Close                            ...   Volume
Symbols     3405.JP  3407.JP  4004.JP 4005.JP  ...  6988.JP 7947.JP 7988.JP  8113.JP
Date                                           ...
2021-02-05  1146.97  1199.30  2615.00  491.41  ...   554543  127433  306328  1956674
2021-02-04  1147.96  1196.84  2622.00  503.08  ...   494429  106934  419703  1427645
2021-02-03  1160.72  1206.21  2631.00  508.92  ...   724644  149143  409249  1084564
2021-02-02  1118.50  1180.06  2610.00  501.15  ...   668933  200943  221778  1175330
2021-02-01  1108.68  1160.31  2558.00  495.31  ...   477429  270617  210308  1047415
...             ...      ...      ...     ...  ...      ...     ...     ...      ...
2020-01-31  1264.77  1101.31  2533.88  450.97  ...   701918  154916  458986  1678384
2020-01-30  1249.62  1091.63  2508.30  449.06  ...   854904  128278  260718  1442934
2020-01-29  1252.47  1095.02  2540.51  452.88  ...   960552  110859  227123  1365292
2020-01-28  1241.09  1073.73  2534.82  450.01  ...  1593920  122745  297197  1308172
2020-01-27  1251.51  1092.60  2542.40  455.75  ...   767125  148358  270095  1828308

[252 rows x 220 columns]
Attributes    Close                    ...    Volume
Symbols     4151.JP  4502.JP  4503.JP  ...   4578.JP   4581.JP   4587.JP
2020-01-27  2596.96  3905.63  1798.12  ...  707688.0  113351.0  298900.0
2020-01-28  2579.34  3882.91  1796.70  ...  670823.0  118401.0  409300.0
2020-01-29  2567.58  3921.09  1803.84  ...  576230.0   89032.0  286800.0
2020-01-30  2528.44  3862.91  1811.92  ...  826033.0  102016.0  470300.0
2020-01-31  2531.38  3842.00  1855.19  ...  827375.0  150035.0  403700.0
...             ...      ...      ...  ...       ...       ...       ...
2021-02-01  3166.36  3555.19  1690.25  ...  625815.0  117974.0  614900.0
2021-02-02  3047.06  3515.08  1692.69  ...  637135.0  134711.0  548000.0
2021-02-03  3071.92  3497.89  1719.01  ...  601963.0   54675.0  408500.0
2021-02-04  3007.30  3495.03  1712.19  ...  775599.0  103976.0  387500.0
2021-02-05  3181.27  3506.49  1759.47  ...  923563.0  102961.0  510700.0

[252 rows x 100 columns]
Attributes    Close                   ...   Volume
Symbols     5019.JP 5020.JP  5021.JP  ...  5019.JP   5020.JP 5021.JP
Date                                  ...
2021-02-05  2397.29  414.38  2210.88  ...   847021  16059928  327861
2021-02-04  2389.61  411.23  2251.64  ...   899205  17432560  198344
2021-02-03  2365.62  405.97  2212.82  ...   752133  17678297  233480
2021-02-02  2348.33  405.97  2186.61  ...   952430  14546905  300041
2021-02-01  2341.61  402.82  2171.08  ...  1295426  17576926  478396
...             ...     ...      ...  ...      ...       ...     ...
2020-01-31  2572.69  423.16  1973.23  ...  1714547  17550650  292413
2020-01-30  2579.21  425.87  1973.23  ...  1656188  14665405  409271
2020-01-29  2595.95  428.67  2011.02  ...  1271643  11491126  266915
2020-01-28  2589.44  426.32  2005.49  ...  2815735  19251508  625190
2020-01-27  2653.64  433.10  2046.04  ...  1605459  12942167  408510

[252 rows x 15 columns]
Attributes    Close                    ...  Volume
Symbols     5101.JP  5105.JP  5108.JP  ... 5105.JP  5108.JP  5110.JP
Date                                   ...
2021-02-05  1766.67  1788.80  4012.56  ...  883748  1986410  1337977
2021-02-04  1736.07  1750.12  4012.56  ...  787134  2047524  1194579
2021-02-03  1728.18  1705.50  3953.26  ...  830600  1731836   951430
2021-02-02  1695.61  1615.27  3862.34  ...  562339  1535441   812488
2021-02-01  1669.95  1595.44  3860.36  ...  614176  1591597   977153
...             ...      ...      ...  ...     ...      ...      ...
2020-01-31  1788.98  1331.22  3707.24  ...  605573  2715269  2683848
2020-01-30  1770.04  1311.01  3704.38  ...  705826  2837016  1034529
2020-01-29  1801.29  1325.44  3721.49  ...  893659  2220071  1347572
2020-01-28  1792.76  1320.63  3680.63  ...  977497  2489452   959811
2020-01-27  1812.66  1335.06  3701.54  ...  932098  2344660   933697

[252 rows x 20 columns]
Attributes    Close                    ...   Volume
Symbols     5201.JP  5214.JP  5232.JP  ...  5332.JP  5333.JP  5334.JP
Date                                   ...
2021-02-05  3813.97  2372.70  3165.76  ...   571539  1299956  2006824
2021-02-04  3735.13  2406.08  3103.02  ...  1037350  1149340  1065847
2021-02-03  3735.13  2431.60  3122.32  ...   661787  1581568  1081456
2021-02-02  3636.58  2333.43  3078.89  ...   825388  1580648  1163842
2021-02-01  3611.94  2323.62  3069.25  ...  1503060  1927759  1125388
...             ...      ...      ...  ...      ...      ...      ...
2020-01-31  3565.97  2009.88  4268.92  ...   980588  1931498  1407427
2020-01-30  3532.73  2018.29  4230.97  ...   717938  1789829  1460470
2020-01-29  3660.94  2057.49  4292.64  ...   354874  1339942  1191452
2020-01-28  3632.45  2067.74  4302.12  ...   607596  1498547   924654
2020-01-27  3689.43  2072.42  4316.35  ...   591424  1388872  1072054

[252 rows x 40 columns]
Attributes    Close                            ...  Volume
Symbols     5401.JP 5406.JP  5411.JP  5444.JP  ... 5444.JP 5463.JP 5471.JP  5486.JP
Date                                           ...
2021-02-05  1293.46  523.07   963.39  2648.54  ...   83350  217072   88309  1110600
2021-02-04  1242.11  506.53   926.93  2624.12  ...   94307  340907   92175   988400
2021-02-03  1245.98  507.51   925.97  2624.12  ...  215134  251894  141519  1743700
2021-02-02  1217.39  497.79   913.49  2652.44  ...  192607  593212  220773   994500
2021-02-01  1183.97  489.03   896.22  2631.94  ...   72496  589401  237356   854400
...             ...     ...      ...      ...  ...     ...     ...     ...      ...
2020-01-31  1487.72  492.93  1261.81  2524.13  ...  254089  223654  203086  3033072
2020-01-30  1478.02  486.12  1255.09  2488.32  ...  306945  150868  128418  2378303
2020-01-29  1485.29  495.85  1286.76  2522.24  ...  296226  130738  210336   995350
2020-01-28  1489.65  496.81  1280.04  2472.31  ...  356405  204266  285108  1724950
2020-01-27  1535.19  511.39  1324.19  2459.12  ...  217685  163582  183099  1002631

[252 rows x 35 columns]
Attributes    Close                    ...  Volume
Symbols     5703.JP  5706.JP  5711.JP  ... 5714.JP  5801.JP  5802.JP
Date                                   ...
2021-02-05  1961.41  3746.35  2365.54  ...  263616  2900156  3651724
2021-02-04  1930.01  3770.90  2345.09  ...  169424   988616  5937012
2021-02-03  1905.27  3756.17  2325.62  ...  298989   737566  4828580
2021-02-02  1877.67  3775.81  2330.49  ...  397667  1070907  3161058
2021-02-01  1833.89  3697.25  2224.34  ...  206937  1020290  1515183
...             ...      ...      ...  ...     ...      ...      ...
2020-01-31  1959.61  2490.70  2663.12  ...  203175   561255  2522180
2020-01-30  1931.82  2463.28  2642.07  ...  303132   719307  3188353
2020-01-29  1922.59  2511.51  2666.95  ...  179501   445690  3650339
2020-01-28  1876.43  2504.88  2644.94  ...  291874   815221  2748252
2020-01-27  1931.82  2487.86  2690.87  ...  267883   952242  2435375

[252 rows x 35 columns]
Attributes    Close                    ...   Volume
Symbols     3436.JP  5901.JP  5929.JP  ...  5938.JP 5947.JP  5991.JP
Date                                   ...
2021-02-05  2271.00  1222.09  1279.87  ...  2934746  169111  1239500
2021-02-04  2277.00  1149.69  1241.73  ...  1006596  105505   610700
2021-02-03  2367.00  1136.97  1241.73  ...  1443989  110654   591200
2021-02-02  2398.00  1105.66  1214.35  ...  1202062  108635   486700
2021-02-01  2292.00  1097.84  1207.51  ...  1644981  179409   352900
...             ...      ...      ...  ...      ...     ...      ...
2020-01-31  1732.84  1814.07  1100.97  ...  3422598  106820   367500
2020-01-30  1713.92  1780.22  1101.92  ...  1335794   85273   248400
2020-01-29  1780.65  1813.11  1111.36  ...  1216821   93404   356400
2020-01-28  1769.69  1816.97  1123.63  ...  2428812  100822   470500
2020-01-27  1820.48  1823.73  1134.96  ...  1293792   86289   460000

[252 rows x 30 columns]
Attributes    Close                    ...   Volume
Symbols     5631.JP  6005.JP  6103.JP  ...  6586.JP  7011.JP  7013.JP
Date                                   ...
2021-02-05  3066.07  5924.06  6152.26  ...  1043217  2728253  2614931
2021-02-04  3006.92  6013.52  6063.10  ...   797136  2317496  1256659
2021-02-03  3070.99  6073.15  6191.90  ...   562472  1320831  2291692
2021-02-02  3130.15  6073.15  6261.24  ...  1300316   897215  1369494
2021-02-01  3031.56  6013.52  6092.82  ...  1814613  1169222  1638035
...             ...      ...      ...  ...      ...      ...      ...
2020-01-31  1929.83  3808.52  4955.49  ...  1747464  1153660  1162721
2020-01-30  1919.21  3823.36  4906.99  ...   844230  1146742  2137687
2020-01-29  2012.85  3887.66  5062.16  ...   468627   842867   820291
2020-01-28  1987.74  3862.93  4974.88  ...   674340  1068192  1293992
2020-01-27  2019.61  3862.93  5052.47  ...   375403   917798   709824

[252 rows x 160 columns]
Attributes   Close                   ...    Volume
Symbols    3105.JP  4062.JP 4902.JP  ...   7751.JP   7752.JP  8035.JP
Date                                 ...
2021-02-05  833.97  4953.80  497.50  ...   4585542  11083866   859222
2021-02-04  814.28  5187.33  475.63  ...   5710531   4015496   841326
2021-02-03  823.14  5048.20  455.66  ...   6207847   3083314   769538
2021-02-02  797.54  5008.46  451.85  ...   4464037   4671901   893489
2021-02-01  787.69  4928.96  441.38  ...   7818246   4422695   985208
...            ...      ...     ...  ...       ...       ...      ...
2020-01-31  907.73  2515.47  626.52  ...   5403683   2887258  1665956
2020-01-30  904.87  2490.94  619.14  ...  11063998   2871935  1703705
2020-01-29  924.77  2569.44  655.08  ...   2369685   2780939  1264797
2020-01-28  915.30  2557.66  642.17  ...   3211211   3546284  1197224
2020-01-27  936.15  2570.42  649.55  ...   2266596   2017146  1101808

[252 rows x 255 columns]
Attributes    Close                    ...   Volume
Symbols     3116.JP  6201.JP  6902.JP  ...  7282.JP 7309.JP 7313.JP
Date                                   ...
2021-02-05  1815.81  9512.55  6601.16  ...   419175  259767  462776
2021-02-04  1806.11  9394.38  6584.47  ...   515995  255855  386135
2021-02-03  1831.32  9089.11  6478.48  ...   880811  221554  452126
2021-02-02  1745.04  8852.78  6233.12  ...  1072195  165689  601442
2021-02-01  1714.99  8261.94  5815.03  ...   262767  188757  446696
...             ...      ...      ...  ...      ...     ...     ...
2020-01-31  1521.16  5820.88  4372.86  ...   724529  182296  450356
2020-01-30  1511.66  6024.61  4413.30  ...   475974  157553  259771
2020-01-29  1539.20  6131.33  4398.85  ...   287916  102207  362068
2020-01-28  1534.46  6102.23  4398.85  ...   359557  174015  505112
2020-01-27  1559.13  6092.53  4477.79  ...   373823  163209  225602

[252 rows x 95 columns]
Attributes    Close                    ...   Volume
Symbols     4543.JP  7701.JP  7730.JP  ...  7747.JP 7780.JP 8086.JP
Date                                   ...
2021-02-05  4383.26  4023.46  2789.39  ...  1314888  275190  813285
2021-02-04  4134.84  4043.33  2759.68  ...   363240  234214  782749
2021-02-03  4218.30  4068.17  2815.13  ...   503820  349714  688479
2021-02-02  4151.73  4038.36  2778.50  ...   399965  336054  351771
2021-02-01  4078.19  3988.69  2747.80  ...   524089  286440  441635
...             ...      ...      ...  ...      ...     ...     ...
2020-01-31  3930.98  3071.12  2722.17  ...   570830  584250  367314
2020-01-30  3864.87  3100.65  2738.86  ...  1096349  604056  407663
2020-01-29  3895.45  3174.48  2824.27  ...   442950  319104  319666
2020-01-28  3849.08  3159.72  2854.70  ...   538709  267166  407975
2020-01-27  3886.56  3149.88  2895.93  ...   375184  345174  436544

[252 rows x 50 columns]
Attributes    Close                    ...  Volume
Symbols     7832.JP  7846.JP  7911.JP  ... 7966.JP  7974.JP 7984.JP
Date                                   ...
2021-02-05  8843.29  3095.43  1573.14  ...  275352  1098546  251043
2021-02-04  8864.17  3035.91  1521.22  ...  132936   736124  217665
2021-02-03  9010.39  3055.75  1539.83  ...  122837   991602  197841
2021-02-02  9033.26  2951.57  1512.41  ...  131184  2115827  333780
2021-02-01  9090.95  2942.65  1490.86  ...  174156  1002981  235163
...             ...      ...      ...  ...     ...      ...     ...
2020-01-31  6303.72  4229.95  2126.72  ...  122729  2627740  196090
2020-01-30  6176.22  4151.98  2117.04  ...   98461  1172585  227709
2020-01-29  6361.05  4229.95  2167.40  ...  174248   830993  223117
2020-01-28  6361.05  4176.34  2146.09  ...  153705   994705  306187
2020-01-27  6334.36  4166.60  2172.24  ...  182337   990932  212890

[252 rows x 50 columns]
Attributes   Close                    ...   Volume
Symbols    9501.JP  9502.JP  9503.JP  ...  9531.JP  9532.JP 9533.JP
Date                                  ...
2021-02-05   399.0  1281.80  1016.77  ...  1559616  1035383  195999
2021-02-04   400.0  1269.74   990.91  ...  1163888  1095324  160574
2021-02-03   384.0  1262.50   986.12  ...  1711093  1347484  270381
2021-02-02   375.0  1248.03   977.97  ...  1927737  1759075  260188
2021-02-01   397.0  1255.27   987.08  ...  2149308  1113050  180053
...            ...      ...      ...  ...      ...      ...     ...
2020-01-31   435.0  1385.70  1151.19  ...  1960573  1564692  194208
2020-01-30   429.0  1379.17  1153.07  ...  1182733  1119842  182539
2020-01-29   431.0  1374.06  1139.01  ...  1185781   845206  164985
2020-01-28   431.0  1360.08  1133.38  ...  1652252   985095  144489
2020-01-27   429.0  1358.69  1138.54  ...  1400785  1100532  136574

[252 rows x 65 columns]
Attributes    Close                    ...  Volume
Symbols     9001.JP  9003.JP  9005.JP  ... 9086.JP  9142.JP  9143.JP
Date                                   ...
2021-02-05  3099.64  2594.08  1383.45  ...  141759  1583792   987225

# 各銘柄の上昇率を計算

In [12]:
stock_price

Attributes    Close                             ...  Volume
Symbols     2127.JP  2175.JP  2181.JP  2331.JP  ... 8876.JP 9735.JP 9744.JP 9783.JP
Date                                            ...
2021-02-05  2999.14  3899.04  2088.43  5019.79  ...  380629  607480   84242  930163
2021-02-04  3009.07  3953.89  1984.56  5009.93  ...  196964  337070   64185  469675
2021-02-03  3004.11  4138.37  2042.93  5029.66  ...  346979  465089   65522  434865
2021-02-02  3038.86  4153.33  1939.04  4950.75  ...  284313  330852   38058  415572
2021-02-01  3023.96  4068.57  1958.83  4921.17  ...  311918  377432   50916  284092
...             ...      ...      ...      ...  ...     ...     ...     ...     ...
2020-01-31  1572.56  2722.96  1938.12  5558.72  ...  449094  643432  222061  338800
2020-01-30  1884.10  2671.32  1908.83  5529.51  ...  456952  532889  216514  382643
2020-01-29  1948.38  2749.77  1915.66  5568.45  ...  332840  640630  127136  307527
2020-01-28  1960.76  2780.56  1921.53  5733.95  ...  405306  420790  129695  271477
2020-01-27  1955.81  2799.42  1951.79  5763.15  ...  306812  523652   73379  296722

[252 rows x 135 columns]

In [14]:
stock_price.to_csv("topix500_data.csv")

In [15]:
print(list(stock_price.columns))

[('Close', '2127.JP'), ('Close', '2175.JP'), ('Close', '2181.JP'), ('Close', '2331.JP'), ('Close', '2371.JP'), ('Close', '2412.JP'), ('Close', '2413.JP'), ('Close', '2427.JP'), ('Close', '2432.JP'), ('Close', '2433.JP'), ('Close', '2492.JP'), ('Close', '4324.JP'), ('Close', '4544.JP'), ('Close', '4661.JP'), ('Close', '4665.JP'), ('Close', '4681.JP'), ('Close', '4732.JP'), ('Close', '4751.JP'), ('Close', '4755.JP'), ('Close', '6028.JP'), ('Close', '6098.JP'), ('Close', '6178.JP'), ('Close', '6532.JP'), ('Close', '8876.JP'), ('Close', '9735.JP'), ('Close', '9744.JP'), ('Close', '9783.JP'), ('High', '2127.JP'), ('High', '2175.JP'), ('High', '2181.JP'), ('High', '2331.JP'), ('High', '2371.JP'), ('High', '2412.JP'), ('High', '2413.JP'), ('High', '2427.JP'), ('High', '2432.JP'), ('High', '2433.JP'), ('High', '2492.JP'), ('High', '4324.JP'), ('High', '4544.JP'), ('High', '4661.JP'), ('High', '4665.JP'), ('High', '4681.JP'), ('High', '4732.JP'), ('High', '4751.JP'), ('High', '4755.JP'), ('High', '6028.JP'), ('High', '6098.JP'), ('High', '6178.JP'), ('High', '6532.JP'), ('High', '8876.JP'), ('High', '9735.JP'), ('High', '9744.JP'), ('High', '9783.JP'), ('Low', '2127.JP'), ('Low', '2175.JP'), ('Low', '2181.JP'), ('Low', '2331.JP'), ('Low', '2371.JP'), ('Low', '2412.JP'), ('Low', '2413.JP'), ('Low', '2427.JP'), ('Low', '2432.JP'), ('Low', '2433.JP'), ('Low', '2492.JP'), ('Low', '4324.JP'), ('Low', '4544.JP'), ('Low', '4661.JP'), ('Low', '4665.JP'), ('Low', '4681.JP'), ('Low', '4732.JP'), ('Low', '4751.JP'), ('Low', '4755.JP'), ('Low', '6028.JP'), ('Low', '6098.JP'), ('Low', '6178.JP'), ('Low', '6532.JP'), ('Low', '8876.JP'), ('Low', '9735.JP'), ('Low', '9744.JP'), ('Low', '9783.JP'), ('Open', '2127.JP'), ('Open', '2175.JP'), ('Open', '2181.JP'), ('Open', '2331.JP'), ('Open', '2371.JP'), ('Open', '2412.JP'), ('Open', '2413.JP'), ('Open', '2427.JP'), ('Open', '2432.JP'), ('Open', '2433.JP'), ('Open', '2492.JP'), ('Open', '4324.JP'), ('Open', '4544.JP'), ('Open', '4661.JP'), ('Open', '4665.JP'), ('Open', '4681.JP'), ('Open', '4732.JP'), ('Open', '4751.JP'), ('Open', '4755.JP'), ('Open', '6028.JP'), ('Open', '6098.JP'), ('Open', '6178.JP'), ('Open', '6532.JP'), ('Open', '8876.JP'), ('Open', '9735.JP'), ('Open', '9744.JP'), ('Open', '9783.JP'), ('Volume', '2127.JP'), ('Volume', '2175.JP'), ('Volume', '2181.JP'), ('Volume', '2331.JP'), ('Volume', '2371.JP'), ('Volume', '2412.JP'), ('Volume', '2413.JP'), ('Volume', '2427.JP'), ('Volume', '2432.JP'), ('Volume', '2433.JP'), ('Volume', '2492.JP'), ('Volume', '4324.JP'), ('Volume', '4544.JP'), ('Volume', '4661.JP'), ('Volume', '4665.JP'), ('Volume', '4681.JP'), ('Volume', '4732.JP'), ('Volume', '4751.JP'), ('Volume', '4755.JP'), ('Volume', '6028.JP'), ('Volume', '6098.JP'), ('Volume', '6178.JP'), ('Volume', '6532.JP'), ('Volume', '8876.JP'), ('Volume', '9735.JP'), ('Volume', '9744.JP'), ('Volume', '9783.JP')]

In [16]:
# 銘柄ごとに上昇率を計算し、ディショクナリに格納する
dict = {}
for symbol in symbols:
    
    # 基準日付からの上昇率を計算する
    # base_data
    base_date_str = base_date.strftime('%04Y-%02m-%02d')
    base_price = stock_price.loc[base_date_str][('Close',symbol)]
    increase_rate = stock_price[('Close',symbol)] / base_price.iloc[0]
    
    # ディクショナリに格納する
    dict[symbol] = increase_rate
    
# ディクショナリからDataFrame作成
df = pd.DataFrame(dict)

# 業種ごとの平均値, 標準偏差を算出

In [22]:
mean = df.mean(axis='columns')

std = df.std(axis='columns')
category_df = pd.concat([mean, std], axis=1)
category_df

                   0         1
Date
2021-02-05  1.223140  0.421133
2021-02-04  1.211320  0.430671
2021-02-03  1.226722  0.448523
2021-02-02  1.209513  0.462150
2021-02-01  1.189828  0.455865
...              ...       ...
2020-01-31  0.982190  0.054702
2020-01-30  0.981390  0.031962
2020-01-29  0.994076  0.017545
2020-01-28  0.992692  0.009174
2020-01-27  1.000000  0.000000

[252 rows x 2 columns]

In [ ]:
# 業種内銘柄の上昇率の平均値を計算する
mean = df.mean(axis='columns')
std = df.std(axis='columns')

# DataFrameに業種単位の上昇率と、上昇率の標準偏差を格納する
if category_df is None:
    category_df = pd.concat([mean, std], axis=1)
    category_df.columns = pd.MultiIndex.from_tuples(
        [(category_class, '上昇率'), (category_class, '標準偏差')])
else:
    category_df[(category_class, '上昇率')] = mean
    category_df[(category_class, '標準偏差')] = std

print(category_df)

               サービス業
                 上昇率      標準偏差
Date
2021-02-05  1.223140  0.421133
2021-02-04  1.211320  0.430671
2021-02-03  1.226722  0.448523
2021-02-02  1.209513  0.462150
2021-02-01  1.189828  0.455865
...              ...       ...
2020-01-31  0.982190  0.054702
2020-01-30  0.981390  0.031962
2020-01-29  0.994076  0.017545
2020-01-28  0.992692  0.009174
2020-01-27  1.000000  0.000000

[252 rows x 2 columns]

# 折れ線グラフで株価上昇率を可視化

In [24]:
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

In [25]:
# 上昇率のみを抽出し、業種の数を取得する
increase_rate_df = category_df.loc[:, pd.IndexSlice[:, '上昇率']]
industry_num = len(increase_rate_df.columns)

# rows, colsを決定し、Figureを取得
rows, cols = (6, 6)
fig = plt.figure(figsize=(20, 16))

# 上昇率の最大値と最小値を取得
min_y = increase_rate_df.min().min()
max_y = increase_rate_df.max().max()

TypeError: ignored